### ISSUE TITLE
checking task.customer_review_status for non-reviewed images throws an expcetion

### ISSUE THREAD

**Issue by ogail** [scaleapi/scaleapi-python-client#10]
When downloading annotated tasks, I want to fetch only ones with accepted customer review status. Currently, this property will be added to the response payload only when the image is reviewed. However `Task.py` throws an exception because of how `__getattr__` method is implemented. Ideally, it should return `"nonspecified"` or just empty string `""` indicating there is not customer review yet.

Aside, I suggest avoiding this confusion at all by doing filtering on server side by updating [list all tasks api](https://docs.scaleapi.com/#list-all-tasks) to provide a filter based on `customer_review_status`

**Comment by fatihkurtoglu** [comment]
Tasks are now can be filtered based on `customer_review_status` on Scale API as well as via SDK method `get_tasks()`.

Here is a sample code:
```python
import scaleapi
from scaleapi.tasks import TaskReviewStatus

client = scaleapi.ScaleClient('your_API_key_here')

tasks = client.get_tasks(project_name='My Project', 
                         review_status=TaskReviewStatus.Accepted)

print("Accepted Tasks:")
for task in tasks:
    print(task.id)
```

Refer to scaleapi.tasks.TaskReviewStatus Enum for the list of options for `customer_review_status`.
