### ISSUE TITLE
client.get_batches() missing query parameters

### ISSUE THREAD

**Issue by Gaurangkarwande** [scaleapi/scaleapi-python-client#60]
The current supported optional parameters for the function get_batches() are `project_name`, `batch_status`, `created_after` and `created_before`. However the API documentation shows more optional query params like `audited_after`, `limit`, `offset`, etc.
Will the method be supporting these parameters in the future?

**Comment by shaun-scale** [comment]
Hi @Gaurangkarwande , thanks for calling out this discrepancy - it was not an intentional omission, we do intend to have the SDK remain at parity with the API. 

cc @jonathanfeng-scale
