### ISSUE TITLE
Hypothesis Format for SegmentAnnotation task

### ISSUE THREAD

**Issue by umesh-timalsina** [scaleapi/scaleapi-python-client#62]
I wanted to check the correct format for the hypothesis for a task. I checked the API documentation and couldn't find the right reference for it. Should it be an image that has pixel values as labels for the task? or should it be something else?

**Comment by shaun-scale** [comment]
Hi @umesh-timalsina !

Did you come across this page in our docs already?
https://docs.scale.com/reference/image-segmentation-hypothesis

This is the starting point we'd recommend, let us know if there were any gaps here that still left you a bit stuck!
